# Generated by Django 3.1.2 on 2023-05-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
        ('lmn', '0003_auto_20230430_1409'),
    ]

    operations = [
    ]
